const MainScrptQues = [
  {
    id: 1,
    q: "Tony's AutoParts Store is a small retailer. Tony Brown owns the business and has purchased a microcomputer system equipped with bar coding devices. Tony Brown has asked Chery James, accountant, what she thinks of implementing a perpetual inventory system. Which one of the following statements is correct?",
    options: [
      "A. A perpetual system is cheaper to administer than a periodic system.",
      "B. The cost of implementing and administering a perpetual system for Tony's AutoParts Store would probably exceed any savings generated by achieving better control.",
      "C. A perpetual inventory system requires a daily reconciliation between goods sold per the cash register and goods remaining in stock.",
      "D. A perpetual system might eliminate the necessity of having to take a physical inventory every year."
    ],
    answer: 2, // B
    notID: 1,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 2,
    q: "During the month of October, a company purchased 1,000 units of inventory for $500 per unit and sold 900 of these units which represented 10% of the company’s annual sales budget in units. The company also incurred administrative costs of $300,000 during October. By applying the matching principle, the total amount of the company’s expenses on its October income statement is",
    options: [
      "A. $750,000.",
      "B. $800,000.",
      "C. $810,000.",
      "D. $860,000."
    ],
    answer: 1, // c
    notID: 2,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 3,
    q: "DEF is the consignee for 1,000 units of product X for ABC Company. ABC should recognize the revenue from these 1,000 units when",
    options: [
      "A. The agreement between DEF and ABC is signed.",
      "B. ABC ships the goods to DEF.",
      "C. DEF receives the goods from ABC.",
      "D. DEF sells the goods and informs ABC of the sale."
    ],
    answer: 4, // B
    notID: 3,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 4,
    q: "A physical inventory count showed an entity had inventory costing $1,000,000 on hand at December 31, Year 1. Excluded from this amount were the following:<br>1. Goods costing $82,000, shipped to a customer free on board (FOB) shipping point on December 28, Year 1. They were expected to be received by the customer on January 4, Year 2.<br>2. Goods costing $122,000, shipped to a customer free on board (FOB) destination December 30, Year 1. They were expected to be received by the customer on January 5, Year 2.<br>Compute the correct ending inventory to be reported on the shipper’s statement of financial position at December 31, Year 1.",
    options: [
      "A. $1,000,000",
      "B. $1,082,000",
      "C. $1,122,000",
      "D. $1,204,000"
    ],
    answer: 3, // A
    notID: 4,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 5,
    q: "An entity with a December 31 year end purchased $2,000 of inventory on account. The seller was responsible for delivery to the shipping point, with freight of $50 paid at destination by the buyer. The invoice date was December 27, Year 1, and the goods arrived on January 3, Year 2.<br>Now assume the terms required the seller to deliver to the destination instead of the shipping point. What is the correct amount of inventory and freight-in relating to this purchase on the Year 1 financial statements?",
    options: [
      "A. Inventory $0 , Fright In $0",
      "B. Inventory $2,050 , Fright In $0",
      "C. Inventory $0 , Fright In $50",
      "D. Inventory $2,000 , Fright In $50"
    ],
    answer: 1, // D
    notID: 5,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 6,
    q: "A wholesaler using a perpetual inventory system sold and shipped goods FOB Destination on December 31, costing $80,210. These goods are scheduled to reach various retailers on January 3. At the end of the day on December 31, the merchandise inventory account totaled $2,457,820 for the wholesaler before any adjusting entries. This balance excludes the potential impacts of the following:<br>• The wholesaler is expecting a $75,330 incoming shipment that was sent on December 30 (FOB Shipping Point) to arrive on January 2.<br>• Of the existing inventory, it was determined that $20,440 of the goods are obsolete, cannot be sold, and have no scrap value.<br>What is the wholesaler’s true cost of inventory on December 31?",
    options: [
      "A. $2,437,380.",
      "B. $2,512,710.",
      "C. $2,517,590.",
      "D. $2,592,920."
    ],
    answer: 4, // a
    notID: 6,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 7,
    q: "A distributor sells a single product and had a beginning inventory of 10,150 units at a cost of $60,900. During the year, 70,100 units were purchased at $7.50 each. In accordance with U.S. GAAP, and using FIFO, what is the value of the ending inventory consisting of 11,500 units?",
    options: [
      "A. $69,000.",
      "B. $71,025.",
      "C. $84,225.",
      "D. $86,250."
    ],
    answer: 4, // d
    notID: 7,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 8,
    q: `An entity started in Year 1 with 200 scented candles on hand at a cost of $3.50 each. These candles sell for $7.00 each. The following schedule represents the purchases and sales of candles during Year 1:
    <table border="1">
  <tr>
    <th>Transaction Number</th>
    <th>Quantity Purchased</th>
    <th>Unit Cost</th>
    <th>Quantity Sold</th>
  </tr>
  <tr>
    <td>1</td>
    <td>---</td>
    <td>---</td>
    <td>150</td>
  </tr>
  <tr>
    <td>2</td>
    <td>250</td>
    <td>$3.30</td>
    <td>---</td>
  </tr>
  <tr>
    <td>3</td>
    <td>---</td>
    <td>---</td>
    <td>100</td>
  </tr>
  <tr>
    <td>4</td>
    <td>200</td>
    <td>$3.10</td>
    <td>---</td>
  </tr>
  <tr>
    <td>5</td>
    <td>---</td>
    <td>---</td>
    <td>200</td>
  </tr>
  <tr>
    <td>6</td>
    <td>350</td>
    <td>$3.00</td>
    <td>---</td>
  </tr>
  <tr>
    <td>7</td>
    <td>---</td>
    <td>---</td>
    <td>300</td>
  </tr>
</table>If the entity uses periodic FIFO inventory pricing, the gross profit for Year 1 would be`,
    options: [
      "A. $2,755",
      "B. $2,805",
      "C. $2,854",
      "D. $2,920"
    ],
    answer: 2, // B
    notID: 8,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 9,
    q: `A merchandising company had the following inventory related transactions in its first year of operations:<table border="1">
    <tr>
      <th>Date</th>
      <th>Purchases in Units</th>
      <th>Sales in Units</th>
      <th>Balance in Units</th>
    </tr>
    <tr>
      <td>Jan. 1</td>
      <td>10,000 @ $5</td>
      <td></td>
      <td>10,000</td>
    </tr>
    <tr>
      <td>March 1</td>
      <td>6,000 @ $6</td>
      <td></td>
      <td>16,000</td>
    </tr>
    <tr>
      <td>May 1</td>
      <td></td>
      <td>3,000</td>
      <td>13,000</td>
    </tr>
    <tr>
      <td>July 1</td>
      <td>8,000 @ $6.25</td>
      <td></td>
      <td>21,000</td>
    </tr>
    <tr>
      <td>Sept. 1</td>
      <td></td>
      <td>12,000</td>
      <td>9,000</td>
    </tr>
    <tr>
      <td>Nov. 1</td>
      <td>5,000 @ $7</td>
      <td></td>
      <td>14,000</td>
    </tr>
    <tr>
      <td>Dec. 1</td>
      <td></td>
      <td>2,000</td>
      <td>12,000</td>
    </tr>
  </table>If the company uses the first-in-first-out (FIFO) method of inventory valuation, its ending inventory balance (rounded) will be`,
    options: [
      "A. $62,000",
      "B. $70,759",
      "C. $78,750",
      "D. $84,000"
    ],
    answer: 3, // B
    notID: 9,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 10,
    q: `An entity has 8,000 units in inventory on January 1, valued at $10 per unit. During the year, the entity sold 25,000 units and purchased inventory as follows:<table border="1">
    <tr>
      <th>Date</th>
      <th>Quantity Purchased</th>
      <th>Unit Price</th>
    </tr>
    <tr>
      <td>April 1</td>
      <td>15,000 units</td>
      <td>$8</td>
    </tr>
    <tr>
      <td>July 1</td>
      <td>10,000 units</td>
      <td>$9</td>
    </tr>
    <tr>
      <td>October 1</td>
      <td>12,500 units</td>
      <td>$10</td>
    </tr>
  </table><If the entity uses the weighted-average method of inventory valuation, cost of goods sold for the period will be (round to 4 digits)`,
    options: [
      "A. $186,978",
      "B. $197,000",
      "C. $228,023",
      "D. $235,000"
    ],
    answer: 3, // D
    notID: 10,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 11,
    q: `On January 1, a company has no opening inventory balance. The following purchases are made during the year:<table border="1">
    <tr>
      <th>Date</th>
      <th>Units Purchased</th>
      <th>Unit Cost</th>
    </tr>
    <tr>
      <td>January 1</td>
      <td>5,000</td>
      <td>$10.00</td>
    </tr>
    <tr>
      <td>April 1</td>
      <td>5,000</td>
      <td>$9.00</td>
    </tr>
    <tr>
      <td>July 1</td>
      <td>5,000</td>
      <td>$8.00</td>
    </tr>
    <tr>
      <td>October 1</td>
      <td>5,000</td>
      <td>$7.50</td>
    </tr>
  </table>If the company uses the last-in, first-out (LIFO) method of inventory valuation, cost of goods sold for the year will be:`,
    options: [
      "A. $77,500",
      "B. $86,250",
      "C. $87,500",
      "D. $95,000"
    ],
    answer: 1, // C
    notID: 11,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 12,
    q: "On December 1, a company had 1,000 units in inventory valued at $787,500. On December 12, the company purchased 2,000 units for $1,562,400. Sales of 2,400 units were made on December 23, and on December 30, the company purchased another 2,000 units for $1,537,200. If the company uses a periodic system and the weighted-average inventory valuation method, the company’s December 31 balance sheet would report inventory of",
    options: [
      "A. $2,025,660",
      "B. $2,021,292",
      "C. $2,014,740",
      "D. $2,007,180"
    ],
    answer: 2, // A
    notID: 12,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 13,
    q: `Flex Co. uses a periodic inventory system. The following are inventory transactions for the month of January:<table border="1">
    <tr>
      <th>Date</th>
      <th>Action</th>
      <th>Quantity</th>
      <th>Unit Cost</th>
    </tr>
    <tr>
      <td>1/1</td>
      <td>Beginning inventory</td>
      <td>10,000 units</td>
      <td>$3</td>
    </tr>
    <tr>
      <td>1/5</td>
      <td>Purchase</td>
      <td>5,000 units</td>
      <td>$4</td>
    </tr>
    <tr>
      <td>1/15</td>
      <td>Purchase</td>
      <td>5,000 units</td>
      <td>$5</td>
    </tr>
    <tr>
      <td>1/20</td>
      <td>Sales at $10 per unit</td>
      <td>10,000 units</td>
      <td></td>
    </tr>
  </table>Flex uses the average pricing method to determine the value of its inventory. What amount should Flex report as cost of goods sold on its income statement for the month of January?`,
    options: [
      "A. $30,000",
      "B. $37,500",
      "C. $40,000",
      "D. $100,000"
    ],
    answer: 2, // B
    notID: 13,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 14,
    q: `Illustrated below is a perpetual inventory card for the current year.<table border="1">
    <tr>
      <th>Date</th>
      <th>Units Purchased</th>
      <th>Units Sold</th>
      <th>Units Balance</th>
    </tr>
    <tr>
      <td>January 1</td>
      <td></td>
      <td></td>
      <td>0</td>
    </tr>
    <tr>
      <td>January 12</td>
      <td>1,000 @ $2.00</td>
      <td></td>
      <td>1,000</td>
    </tr>
    <tr>
      <td>March 15</td>
      <td></td>
      <td>300</td>
      <td>700</td>
    </tr>
    <tr>
      <td>May 5</td>
      <td>500 @ $2.20</td>
      <td></td>
      <td>1,200</td>
    </tr>
    <tr>
      <td>July 8</td>
      <td></td>
      <td>500</td>
      <td>700</td>
    </tr>
    <tr>
      <td>November 24</td>
      <td>1,000 @ $1.65</td>
      <td></td>
      <td>1,700</td>
    </tr>
  </table>
  <br>Additional information:<br>• The entity had no opening inventory.<br>• The items sold on March 15 were purchased on January 12.<br>• The items sold on July 8 were purchased on May 5.<br>The ending inventory balance under the first-in, first-out (FIFO) method of inventory valuation is`,
    options: [
      "A. $3,050",
      "B. $3,150",
      "C. $3,230",
      "D. $3,430"
    ],
    answer: 2, // D
    notID: 14,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 15,
    q: `Illustrated below is a perpetual inventory card for the current year.<table border="1">
    <tr>
      <th>Date</th>
      <th>Units Purchased</th>
      <th>Units Sold</th>
      <th>Units Balance</th>
    </tr>
    <tr>
      <td>January 1</td>
      <td></td>
      <td></td>
      <td>0</td>
    </tr>
    <tr>
      <td>January 12</td>
      <td>1,000 @ $2.00</td>
      <td></td>
      <td>1,000</td>
    </tr>
    <tr>
      <td>March 15</td>
      <td></td>
      <td>300</td>
      <td>700</td>
    </tr>
    <tr>
      <td>May 5</td>
      <td>500 @ $2.20</td>
      <td></td>
      <td>1,200</td>
    </tr>
    <tr>
      <td>July 8</td>
      <td></td>
      <td>500</td>
      <td>700</td>
    </tr>
    <tr>
      <td>November 24</td>
      <td>1,000 @ $1.65</td>
      <td></td>
      <td>1,700</td>
    </tr>
  </table>
  <br>Additional information:<br>• The entity had no opening inventory.<br>• The items sold on March 15 were purchased on January 12.<br>• The items sold on July 8 were purchased on May 5.<br>The cost of goods sold under the specific identification method of inventory valuation is`,
    options: [
      "A. $1,320",
      "B. $1,520",
      "C. $1,600",
      "D. $1,700"
    ],
    answer: 4, // D
    notID: 15,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 16,
    q: `During January, Metro Co., which maintains a perpetual inventory system, recorded the following information pertaining to its inventory:<table border="1">
    <tr>
      <th></th>
      <th>Units</th>
      <th>Unit cost</th>
      <th>Total cost</th>
      <th>Units on hand</th>
    </tr>
    <tr>
      <td>Balance on 1/1</td>
      <td>1,000</td>
      <td>$1</td>
      <td>$1,000</td>
      <td>1,000</td>
    </tr>
    <tr>
      <td>Purchased on 1/7</td>
      <td>600</td>
      <td>$3</td>
      <td>$1,800</td>
      <td>1,600</td>
    </tr>
    <tr>
      <td>Sold on 1/20</td>
      <td>900</td>
      <td></td>
      <td></td>
      <td>700</td>
    </tr>
    <tr>
      <td>Purchased on 1/25</td>
      <td>400</td>
      <td>$5</td>
      <td>$2,000</td>
      <td>1,100</td>
    </tr>
  </table>Under the moving-average method, what amount should Metro report as inventory at January 31?`,
    options: [
      "A. $2,640",
      "B. $3,225",
      "C. $3,300",
      "D. $3,900"
    ],
    answer: 2, // B
    notID: 16,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 17,
    q: "The operations of the firm may be viewed as a continual series of transactions or as a series of separate ventures. The inventory valuation method that views the firm as a series of separate ventures is",
    options: [
      "A. FIFO",
      "B. LIFO",
      "C. Specific identification.",
      "D. WA"
    ],
    answer: 3, // C
    notID: 17,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 18,
    q: "The inventory method yielding the same inventory measurement and cost of goods sold whether a perpetual or periodic system is used is",
    options: [
      "A. Average cost.",
      "B. FIFO",
      "C. LIFO",
      "D. Either FIFO or LIFO."
    ],
    answer: 2, // A
    notID: 18,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 19,
    q: "The cost of materials has risen steadily over the year. Which of the following methods of estimating the ending balance of the materials inventory account will result in the highest profit, assuming all other variables remain constant?",
    options: [
      "A. LIFO",
      "B. FIFO",
      "C. WA",
      "D. Specific identification"
    ],
    answer: 2, // A
    notID: 19,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 20,
    q: "In periods of inflation, the use of the FIFO method for inventory costing instead of LIFO will lead to",
    options: [
      "A. better overall cash flow.",
      "B. lower current assets.",
      "C. higher gross profit margin.",
      "D. higher inventory turnover ratio."
    ],
    answer: 3, // C
    notID: 20,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 21,
    q: "The advantage of the last-in, first-out inventory method is based on the assumption that",
    options: [
      "A. The most recently incurred costs should be allocated to the cost of goods sold.",
      "B. Costs should be charged to revenue in the order in which they are incurred.",
      "C. Costs should be charged to cost of goods sold at average cost.",
      "D. Current costs should be based on representative or normal conditions of efficiency and volume of operations."
    ],
    answer: 1, // A
    notID: 21,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 22,
    q: "Which one of the following statements reflects a disadvantage of the LIFO inventory valuation method?",
    options: [
      "A. It rarely approximates the physical flow of inventory.",
      "B. Current costs are not matched to the current revenues.",
      "C. It often can cause acceleration of income tax impacts.",
      "D. It can negatively impact a company’s cash flow."
    ],
    answer: 1, // C
    notID: 22,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 23,
    q: "Jordan Inc. is a profitable company with the goal to maximize cash flow. A valid reason for Jordan not to adopt the last-in, first-out (LIFO) method of inventory valuation is",
    options: [
      "A. The company has high administrative costs.",
      "B. Prices are falling.",
      "C. The reduction effect on inventory.",
      "D. Prices are rising."
    ],
    answer: 2, // D
    notID: 23,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 24,
    q: "In a period of rising prices, which one of the following inventory methods usually provides the best matching of expenses against revenues?",
    options: [
      "A. WA",
      "B. FIFO",
      "C. LIFO",
      "D. Specific identification"
    ],
    answer: 3, // B
    notID: 24,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 25,
    q: "In periods of rising costs, which one of the following inventory cost flow assumptions will result in higher cost of sales?",
    options: [
      "A. FIFO",
      "B. LIFO",
      "C. WA",
      "D. Moving average"
    ],
    answer: 2, // B
    notID: 25,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 26,
    q: "Which one of the following actions would result in a decrease in income?",
    options: [
      "A. Liquidating last-in, first-out layers of inventory when prices have been increasing.",
      "B. Changing from first-in, first-out to last-in, first-out inventory method when prices are decreasing.",
      "C. Accelerating purchases at the end of the year when using last-in, first-out inventory method in times of rising prices.",
      "D. Changing the number of last-in, first-out pools."
    ],
    answer: 3, // A
    notID: 26,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 27,
    q: "Which inventory pricing method generally approximates current cost for each of the following?",
    options: [
      "A. Ending Inventory FIFO , COGS FIFO",
      "B. Ending Inventory LIFO , COGS FIFO",
      "C. Ending Inventory FIFO , COGS LIFO",
      "D. Ending Inventory LIFO , COGS LIFO"
    ],
    answer: 3, // A
    notID: 27,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 28,
    q: "Which inventory cost flow method is prohibited according to IFRS?",
    options: [
      "A. FIFO",
      "B. Specific identification",
      "C. WA",
      "D. LIFO"
    ],
    answer: 4, // D
    notID: 28,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 29,
    q: "Which of the following changes in accounting policies resulting from a significant change in the expected pattern of economic benefit will increase profit?",
    options: [
      "A. A change from FIFO to LIFO inventory valuation when costs are rising.",
      "B. A change from FIFO to weighted-average inventory valuation when costs are falling.",
      "C. A change from accelerated to straight-line depreciation in the later years of the depreciable lives of the assets.",
      "D. A change from straight-line to accelerated depreciation in the early years of the depreciable lives of the assets."
    ],
    answer: 2, // A
    notID: 29,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 30,
    q: "The weighted average for the year inventory cost flow method is applicable to which of the following inventory systems?",
    options: [
      "A. Periodic Yes , Perpetual Yes",
      "B. Periodic Yes , Perpetual No",
      "C. Periodic No , Perpetual Yes",
      "D. Periodic No , Perpetual No"
    ],
    answer: 2, // A
    notID: 30,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 31,
    q: `A retailer sells antique replica trunks to customers all over the world. The retailer’s inventory records show the following:
    <table border="1">
  <tr>
    <th>Action</th>
    <th>Quantity (units)</th>
    <th>Cost (each)</th>
  </tr>
  <tr>
    <td>Beginning inventory</td>
    <td>200</td>
    <td>$1,055</td>
  </tr>
  <tr>
    <td>Purchases: June 3</td>
    <td>170</td>
    <td>$1,062</td>
  </tr>
  <tr>
    <td>Purchases: September 18</td>
    <td>190</td>
    <td>$1,070</td>
  </tr>
  <tr>
    <td>Purchases: December 10</td>
    <td>160</td>
    <td>$1,076</td>
  </tr>
</table>The retailer sells 470 units this year. Management is researching whether the company should use last in, first out (LIFO) or first in, first out (FIFO). If the retailer’s management wants to lower the company’s income taxes, which inventory cost flow assumption should it select?`,
    options: [
      "A. FIFO, because the cost of goods sold will be $9,870 higher than LIFO.",
      "B. FIFO, because the operating income will be $840 lower than LIFO.",
      "C. LIFO, because the operating income will be $4,360 lower than FIFO.",
      "D. LIFO, because the cost of goods sold will be $5,250 higher than FIFO."
    ],
    answer: 3, // C
    notID: 31,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 32,
    q: "The following information is available for an entity for the quarter ended March 31, of the current year:<br>Merchandise inventory, as of January 1 of the current year $30,000<br>Sales $200,000<br>Purchases $190,000<br>The gross profit margin is normally 20% of sales. What is the estimated cost of the merchandise inventory at March 31, of the current year?",
    options: [
      "A. $20,000",
      "B. $40,000",
      "C. $60,000",
      "D. $180,000"
    ],
    answer: 3, // C
    notID: 32,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 33,
    q: "The following information applies to the income statement of a company:<br>Gross sales $1,000,000<br>Net sales $900,000<br>Freight-in $10,000<br>Ending inventory $200,000<br>Gross profit margin 40%<br>The company’s cost of goods available for sale is",
    options: [
      "A. $550,000",
      "B. $560,000",
      "C. $740,000",
      "D. $800,000"
    ],
    answer: 3, // A
    notID: 33,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 34,
    q: "The following inventory valuation errors have been discovered for Knox Corporation.<br>• The year 1 year-end inventory was overstated by $23,000.<br>• The year 2 year-end inventory was understated by $61,000.<br>• The year 3 year-end inventory was understated by $17,000.<br>The reported income before taxes for Knox was:<br>Year 1: $138,000<br>Year 2: $254,000<br>Year 3: $168,000<br>Reported income before taxes for year 1, year 2, and year 3, respectively, should have been",
    options: [
      "A. $115,000, $338,000, and $124,000",
      "B. $161,000, $338,000, and $90,000",
      "C. $161,000, $170,000, and $212,000",
      "D. $115,000, $338,000, and $212,000"
    ],
    answer: 1, // C
    notID: 34,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 35,
    q: "Which one of the following errors will result in the overstatement of net income?",
    options: [
      "A. Overstatement of beginning inventory.",
      "B. Overstatement of ending inventory.",
      "C. Overstatement of goodwill amortization.",
      "D. Overstatement of bad debt expense."
    ],
    answer: 2, // B
    notID: 35,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 36,
    q: "An internal auditor performs an analytical procedure to compare the gross margins of various divisional operations with those of other divisions and with the individual division’s performance in previous years. The internal auditor notes a significant increase in the gross margin at one division. The internal auditor does some preliminary investigation and also notes that there were no changes in products, production methods, or divisional management during the year. The most likely cause of the increase in gross margin is",
    options: [
      "A. An increase in the number of competitors selling similar products.",
      "B. A decrease in the number of suppliers of the material used in manufacturing the product.",
      "C. An overstatement of year-end inventory.",
      "D. An understatement of year-end accounts receivable."
    ],
    answer: 3, // C
    notID: 36,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 37,
    q: "A company’s inventory is overstated at December 31 of this year. The result will be",
    options: [
      "A. Understated income this year.",
      "B. Understated retained earnings this year.",
      "C. Understated retained earnings next year.",
      "D. Understated income next year."
    ],
    answer: 4, // D
    notID: 37,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 38,
    q: "All sales and purchases for the year at Ross Corporation are credit transactions. Ross shipped goods via FOB shipping point. In error, the goods were not recorded as a sale and were included in ending inventory. Which one of the following statements is correct?",
    options: [
      "A. Accounts receivable was understated, inventory was overstated, sales were understated, and cost of goods sold was understated.",
      "B. Accounts receivable was not affected, inventory was overstated, sales were understated, and cost of goods sold was understated.",
      "C. Accounts receivable was understated, inventory was not affected, sales were understated, and cost of goods sold was understated.",
      "D. Accounts receivable was understated, inventory was overstated, sales were understated, and cost of goods sold was overstated."
    ],
    answer: 1, // D
    notID: 38,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 39,
    q: "On December 31, Year 1, Johnson Corporation sold on account and shipped merchandise with a list price of $75,000 to Gibsen Company. The terms of the sale were n/30, FOB shipping point. The merchandise arrived at Gibsen on January 5, Year 2. Because of confusion about the shipping terms, the sale was not recorded until January of Year 2 and the merchandise, sold at a markup of 25% of cost, was included in Johnson's inventory on December 31, Year 1. Johnson uses a periodic inventory system. As a result of the above, Johnson's income before income taxes for the year ended December 31, Year 1 was",
    options: [
      "A. Understated by $15,000.",
      "B. Correctly stated.",
      "C. Understated by $75,000.",
      "D. Understated by $18,750."
    ],
    answer: 1, // A
    notID: 39,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 40,
    q: "An item of inventory purchased in year 1 for $25.00 has been incorrectly written down to a net realizable value of $17.50 at the end of year 1. The item is currently selling in year 2 for $50.00, its normal selling price. Which one of the following statements is correct?",
    options: [
      "A. The cost of sales for year 2 will be overstated.",
      "B. The income for year 1 is overstated.",
      "C. The income for year 2 will be overstated.",
      "D. The closing inventory of year 1 is overstated."
    ],
    answer: 3, // D
    notID: 40,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 41,
    q: "During the year 1 year-end physical inventory count at Tequesta Corporation, $40,000 worth of inventory was counted twice. Assuming that the year 2 year-end inventory was correct, the result of the year 1 error was that",
    options: [
      "A. Year 1 cost of goods sold was understated, and year 2 retained earnings was correct.",
      "B. Year 1 cost of goods sold was overstated, and year 2 income was understated.",
      "C. Year 1 retained earnings was understated, and year 2 ending inventory was correct.",
      "D. Year 1 income was overstated, and year 2 ending inventory was overstated."
    ],
    answer: 1, // B
    notID: 41,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 42,
    q: `An entity had the following opening and closing inventory balances during the current year:<table border="1">
    <tr>
      <th>Category</th>
      <th>1/1</th>
      <th>12/31</th>
    </tr>
    <tr>
      <td>Finished goods</td>
      <td>$90,000</td>
      <td>$260,000</td>
    </tr>
    <tr>
      <td>Raw materials</td>
      <td>$105,000</td>
      <td>$130,000</td>
    </tr>
    <tr>
      <td>Work-in-progress</td>
      <td>$220,000</td>
      <td>$175,000</td>
    </tr>
  </table>
  <br>The following transactions and events occurred during the current year:<br>1. $300,000 of raw materials were purchased, of which $20,000 were returned because of defects.<br>2. $600,000 of direct labor costs were incurred.<br>3. $750,000 of production overhead costs were incurred.<br>If the entity’s raw materials inventory as of December 31 of the current year (ending inventory) was miscounted and the true figure was higher than $130,000, one effect on the year-end financial statements would be that`,
    options: [
      "A. Profit is overstated.",
      "B. Cost of goods sold is overstated.",
      "C. Working capital is overstated.",
      "D. Cost of goods produced is understated."
    ],
    answer: 2, // C
    notID: 42,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 43,
    q: "If certain goods owned by an entity were not recorded as a purchase and were not counted in ending inventory, in error, then",
    options: [
      "A. Cost of goods sold for the period will be understated.",
      "B. Cost of goods sold for the period will be overstated.",
      "C. Net income for the period will be understated.",
      "D. There will be no effect on cost of goods sold or profit for the period."
    ],
    answer: 4, // A
    notID: 43,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 44,
    q: "According to the FASB conceptual framework, which of the following attributes would not be used to measure inventory?",
    options: [
      "A. Historical cost",
      "B. Net realizable value",
      "C. Present value of future cash flows",
      "D. Replacement cost"
    ],
    answer: 3, // C
    notID: 44,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 45,
    q: "In accounting for inventories, generally accepted accounting principles require departure from the historical cost principle when the utility of inventory has fallen below cost. Under the “lower-of-cost-or-market” rule, the term “market” means",
    options: [
      "A. Original cost minus allowance for obsolescence.",
      "B. Original cost plus normal profit margin.",
      "C. Replacement cost of the inventory.",
      "D. Original cost minus cost to dispose."
    ],
    answer: 3, // C
    notID: 45,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 46,
    q: "Under the lower-of-cost-or-market method, the replacement cost of an inventory item would be used as the designated market value when",
    options: [
      "A. It is below the net realizable value less the normal profit margin.",
      "B. It is below the net realizable value and above the net realizable value less the normal profit margin.",
      "C. It is above the net realizable value.",
      "D. Regardless of net realizable value."
    ],
    answer: 2, // F
    notID: 46,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 47,
    q: "The replacement cost of an inventory item is below the net realizable value and above the net realizable value less the normal profit margin. The original cost of the inventory item is below the net realizable value less the normal profit margin. Under the lower-of-cost-or-market (LCM) method, the inventory item should be valued at",
    options: [
      "A. Net realizable value.",
      "B. Net realizable value less the normal profit margin.",
      "C. Original cost.",
      "D. Replacement cost."
    ],
    answer: 3, // D
    notID: 47,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 48,
    q: "The lower-of-cost-or-market rule for inventories may be applied to total inventory, to groups of similar items, or to each item. Which application generally results in the lowest inventory amount?",
    options: [
      "A. All applications result in the same amount.",
      "B. Total inventory.",
      "C. Groups of similar items.",
      "D. Separately to each item."
    ],
    answer: 4, // D
    notID: 48,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 49,
    q: `The following data apply to a unit of inventory:<table border="1">
    <tr>
      <th>Description</th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Selling price</td>
      <td>$22</td>
    </tr>
    <tr>
      <td>Normal profit margin</td>
      <td>5%</td>
    </tr>
    <tr>
      <td>Selling cost</td>
      <td>$2</td>
    </tr>
    <tr>
      <td>Replacement cost</td>
      <td>$10</td>
    </tr>
  </table>
  <br>Using the lower-of-cost-or-market (LCM) method of measuring inventory, what is the market amount for this unit of inventory?`,
    options: [
      "A. $10.00",
      "B. $15.00",
      "C. $17.50",
      "D. $20.00"
    ],
    answer: 2, // A
    notID: 49,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 50,
    q: "Based on a physical inventory taken on December 31, a company determined its chocolate inventory on a LIFO basis at $26,000 with a replacement cost of $20,000. The company estimated that, after further processing costs of $12,000, the chocolate could be sold as finished candy bars for $40,000. The company’s normal profit margin is 10% of sales. Under the lower-of-cost-or-market rule, what amount should the company report as chocolate inventory in its December 31 balance sheet?",
    options: [
      "A. $28,000",
      "B. $26,000",
      "C. $24,000",
      "D. $20,000"
    ],
    answer: 3, // C
    notID: 50,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 51,
    q: `A distribution company has determined its December 31 inventory on a LIFO basis at $200,000. Information pertaining to that inventory follows:<table border="1">
    <tr>
      <th>Description</th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Estimated selling price</td>
      <td>$204,000</td>
    </tr>
    <tr>
      <td>Normal profit margin</td>
      <td>$30,000</td>
    </tr>
    <tr>
      <td>Estimated cost of disposal</td>
      <td>$10,000</td>
    </tr>
    <tr>
      <td>Current replacement cost</td>
      <td>$180,000</td>
    </tr>
  </table>
  <br>The company records losses that result from applying the lower-of-cost-or-market rule. At December 31, the loss that the company should recognize is`,
    options: [
      "A. $0",
      "B. $6,000",
      "C. $14,000",
      "D. $20,000"
    ],
    answer: 4, // B
    notID: 51,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: D</div>',
  },
  {
    id: 52,
    q: `A firm has determined its fiscal year-end inventory on a LIFO basis to be $400,000. Information pertaining to that inventory follows:<table border="1">
    <tr>
      <th>Description</th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Estimated selling price</td>
      <td>$408,000</td>
    </tr>
    <tr>
      <td>Normal profit margin</td>
      <td>$60,000</td>
    </tr>
    <tr>
      <td>Estimated cost of disposal</td>
      <td>$20,000</td>
    </tr>
    <tr>
      <td>Current replacement cost</td>
      <td>$360,000</td>
    </tr>
  </table>
  <br>The firm records losses that result from applying the lower-of-cost-or-market (LCM) rule. At its year end, what should be the net carrying value of the firm’s inventory?`,
    options: [
      "A. $400,000",
      "B. $388,000",
      "C. $360,000",
      "D. $328,000"
    ],
    answer: 3, // C
    notID: 52,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 53,
    q: `A company uses IFRS to value its inventory of frozen foods. The company applies IFRS on a total inventory basis, not directly to each item of frozen food. Information on the frozen food inventory at December 31 of the year just ended is provided below.<table border="1">
    <tr>
      <th>Description</th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Replacement cost</td>
      <td>$80,000</td>
    </tr>
    <tr>
      <td>Weighted-average cost</td>
      <td>$90,000</td>
    </tr>
    <tr>
      <td>Net realizable value less profit margin</td>
      <td>$85,000</td>
    </tr>
    <tr>
      <td>Net realizable value</td>
      <td>$100,000</td>
    </tr>
  </table>The company should value its inventory at`,
    options: [
      "A. $80,000",
      "B. $85,000",
      "C. $90,000",
      "D. $100,000"
    ],
    answer: 3, // A
    notID: 53,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 54,
    q: `Stockholm Co. accounts for its inventory using the first in, first out (FIFO) method. The data below concern items in Stockholm Co.’s inventory.<table border="1">
    <tr>
      <th></th>
      <th>Gear</th>
      <th>Stuff</th>
      <th>Wickets</th>
    </tr>
    <tr>
      <td>Historical cost</td>
      <td>$190.00</td>
      <td>$106.00</td>
      <td>$53.00</td>
    </tr>
    <tr>
      <td>Selling price</td>
      <td>$217.00</td>
      <td>$145.00</td>
      <td>$73.75</td>
    </tr>
    <tr>
      <td>Cost to complete and sell</td>
      <td>$19.00</td>
      <td>$8.00</td>
      <td>$2.50</td>
    </tr>
    <tr>
      <td>Current replacement cost</td>
      <td>$203.00</td>
      <td>$105.00</td>
      <td>$51.00</td>
    </tr>
    <tr>
      <td>Normal profit margin</td>
      <td>$32.00</td>
      <td>$29.00</td>
      <td>$21.25</td>
    </tr>
  </table>
  <br>Under IFRS, what amount should Stockholm Co. compare with historical cost to measure the amount at which the wickets should be measured?`,
    options: [
      "A. $51.00",
      "B. $50.00",
      "C. $71.25",
      "D. $73.75"
    ],
    answer: 3, // A
    notID: 54,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: C</div>',
  },
  {
    id: 55,
    q: `An entity that prepares its financial statements using IFRS reported the following selected per-unit data relating to work-in-process:<table border="1">
    <tr>
      <th></th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Selling price</td>
      <td>$100</td>
    </tr>
    <tr>
      <td>Historical cost</td>
      <td>$91</td>
    </tr>
    <tr>
      <td>Normal gross profit</td>
      <td>$20</td>
    </tr>
    <tr>
      <td>Completion costs</td>
      <td>$10</td>
    </tr>
    <tr>
      <td>Replacement cost</td>
      <td>$108</td>
    </tr>
    <tr>
      <td>Selling cost</td>
      <td>$5</td>
    </tr>
  </table>In comparison with historical cost, what will be the per-unit effect on gross profit of measuring ending inventory?`,
    options: [
      "A. No effect.",
      "B. Reduction of $6.",
      "C. Reduction of $26.",
      "D. Increase of $5."
    ],
    answer: 2, // B
    notID: 55,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 56,
    q: `A company determined the following information for its FIFO basis inventory at the end of an interim period on June 30, Year 2:<table border="1">
    <tr>
      <th>Description</th>
      <th>Amount</th>
    </tr>
    <tr>
      <td>Historical cost</td>
      <td>$80,000</td>
    </tr>
    <tr>
      <td>Current replacement cost</td>
      <td>$76,000</td>
    </tr>
    <tr>
      <td>Net realizable value (NRV)</td>
      <td>$77,000</td>
    </tr>
    <tr>
      <td>Normal profit margin</td>
      <td>$2,000</td>
    </tr>
  </table>The company expects that on December 31, Year 2, the inventory’s NRV will be at least $81,000. What amount of inventory should the company report in its interim financial statements under IFRS and under U.S. GAAP on June 30, Year 2?`,
    options: [
      "IFRS $77,000 , U.S. GAAP $80,000",
      "IFRS $77,000 , U.S. GAAP $77,000",
      "IFRS $80,000 , U.S. GAAP $80,000",
      "IFRS $80,000 , U.S. GAAP $81,000"
    ],
    answer: 1, // A
    notID: 56,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 57,
    q: "Which of the following is true regarding inventory adjustments under IFRS?",
    options: [
      "A. IFRS do not require inventory adjustments.",
      "B. Reversals of adjustments are allowed in a subsequent period.",
      "C. A reversal of a previous write-down may be higher than the previous write-down.",
      "D. Adjustments may not be reversed in a subsequent period."
    ],
    answer: 2, // B
    notID: 57,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  },
  {
    id: 58,
    q: "A fundamental difference between U.S. GAAP and IFRS is that",
    options: [
      "A. reversal of inventory write-downs is prohibited under U.S. GAAP but is permitted under IFRS.",
      "B. distribution costs are included in cost of sales under U.S. GAAP but are excluded from cost of sales under IFRS.",
      "C. inventory is generally valued at the lower of cost or net realizable value under U.S. GAAP but is generally valued at the lower of cost or market under IFRS .",
      "D. marketing costs are included in cost of sales under U.S. GAAP but are excluded from cost of sales under IFRS."
    ],
    answer: 1, // A
    notID: 58,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: A</div>',
  },
  {
    id: 59,
    q: "A multinational company maintains its financial records under both IFRS and U.S. GAAP. Last year, the company determined its inventory was impaired because demand for its product collapsed when a competitor launched a new product with innovative features. As a result, the company wrote down its inventory to $0 with a carrying amount of $500,000. This year, however, government authorities unexpectedly announced that the competitor’s product was defective and the product was removed from the market. As a result, the company’s products were again in demand and the company estimated their net realizable value to be $750,000 at the end of the current quarter. How should the company record this new development in the current quarter?",
    options: [
      "A. Under IFRS, $0 write-up of the inventory; under U.S. GAAP, $0 write-up of the inventory.",
      "B. Under IFRS, $500,000 write-up of the inventory; under U.S. GAAP, $0 write-up of the inventory.",
      "C. Under IFRS, $750,000 write-up of the inventory; under U.S. GAAP, $0 write-up of the inventory.",
      "D. Under IFRS, $750,000 write-up of the inventory; under U.S. GAAP, $750,000 write-up of the inventory."
    ],
    answer: 2, // C
    notID: 59,
    yourAns: "",
    yourNote: "",
    yourChck: "",
    id2: 1,
    ansExplain:
      '<div class="ExplnAns">Correct answer: B</div>',
  }
];
function updateElementWithArrayCount(array) {
  var count = array.length;

  // Multiply by 2
  var result = count * 2;

  if (result > 360) {
    result = 360;
  }

  var element = document.getElementById("timeinmins");

  if (element) {
    element.textContent = result;
  } else {
    console.error("Element not found");
  }
}
updateElementWithArrayCount(MainScrptQues);
